version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    # env_file: .env
    # depends_on:
    #   - mongo-server
    volumes:
      - .:/code
  # mongo-server:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"